// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Alerts.Active
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetStatusQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "actual")]
        #pragma warning disable CS1591
        Actual,
        #pragma warning restore CS1591
        [EnumMember(Value = "exercise")]
        #pragma warning disable CS1591
        Exercise,
        #pragma warning restore CS1591
        [EnumMember(Value = "system")]
        #pragma warning disable CS1591
        System,
        #pragma warning restore CS1591
        [EnumMember(Value = "test")]
        #pragma warning disable CS1591
        Test,
        #pragma warning restore CS1591
        [EnumMember(Value = "draft")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
    }
}
