// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Offices.Item.Weatherstories.Download.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Nws.OpenApiClient.Offices.Item.Weatherstories.Download
{
    /// <summary>
    /// Builds and executes requests for operations under \offices\{officeId}\weatherstories\download
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DownloadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Nws.OpenApiClient.offices.item.weatherstories.download.item collection</summary>
        /// <param name="position">.</param>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Offices.Item.Weatherstories.Download.Item.WithImageItemRequestBuilder"/></returns>
        public global::Soenneker.Nws.OpenApiClient.Offices.Item.Weatherstories.Download.Item.WithImageItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("imageId", position);
                return new global::Soenneker.Nws.OpenApiClient.Offices.Item.Weatherstories.Download.Item.WithImageItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Offices.Item.Weatherstories.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/offices/{officeId}/weatherstories/download", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Offices.Item.Weatherstories.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/offices/{officeId}/weatherstories/download", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
