// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    /// <summary>The code denoting the category of the subject event of the alert message.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Alert_category
    {
        [EnumMember(Value = "Met")]
        #pragma warning disable CS1591
        Met,
        #pragma warning restore CS1591
        [EnumMember(Value = "Geo")]
        #pragma warning disable CS1591
        Geo,
        #pragma warning restore CS1591
        [EnumMember(Value = "Safety")]
        #pragma warning disable CS1591
        Safety,
        #pragma warning restore CS1591
        [EnumMember(Value = "Security")]
        #pragma warning disable CS1591
        Security,
        #pragma warning restore CS1591
        [EnumMember(Value = "Rescue")]
        #pragma warning disable CS1591
        Rescue,
        #pragma warning restore CS1591
        [EnumMember(Value = "Fire")]
        #pragma warning disable CS1591
        Fire,
        #pragma warning restore CS1591
        [EnumMember(Value = "Health")]
        #pragma warning disable CS1591
        Health,
        #pragma warning restore CS1591
        [EnumMember(Value = "Env")]
        #pragma warning disable CS1591
        Env,
        #pragma warning restore CS1591
        [EnumMember(Value = "Transport")]
        #pragma warning disable CS1591
        Transport,
        #pragma warning restore CS1591
        [EnumMember(Value = "Infra")]
        #pragma warning disable CS1591
        Infra,
        #pragma warning restore CS1591
        [EnumMember(Value = "CBRNE")]
        #pragma warning disable CS1591
        CBRNE,
        #pragma warning restore CS1591
        [EnumMember(Value = "Other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
