// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AlertRegionType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "land")]
        #pragma warning disable CS1591
        Land,
        #pragma warning restore CS1591
        [EnumMember(Value = "marine")]
        #pragma warning disable CS1591
        Marine,
        #pragma warning restore CS1591
    }
}
