// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AlertMessageType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Alert")]
        #pragma warning disable CS1591
        Alert,
        #pragma warning restore CS1591
        [EnumMember(Value = "Update")]
        #pragma warning disable CS1591
        Update,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cancel")]
        #pragma warning disable CS1591
        Cancel,
        #pragma warning restore CS1591
        [EnumMember(Value = "Ack")]
        #pragma warning disable CS1591
        Ack,
        #pragma warning restore CS1591
        [EnumMember(Value = "Error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
