// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CenterWeatherAdvisory : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Three-letter identifier for a Center Weather Service Unit (CWSU).</summary>
        public global::Soenneker.Nws.OpenApiClient.Models.NWSCenterWeatherServiceUnitId? Cwsu { get; set; }
        /// <summary>The end property</summary>
        public DateTimeOffset? End { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The issueTime property</summary>
        public DateTimeOffset? IssueTime { get; set; }
        /// <summary>The observedProperty property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObservedProperty { get; set; }
#nullable restore
#else
        public string ObservedProperty { get; set; }
#endif
        /// <summary>The sequence property</summary>
        public int? Sequence { get; set; }
        /// <summary>The start property</summary>
        public DateTimeOffset? Start { get; set; }
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Models.CenterWeatherAdvisory"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Nws.OpenApiClient.Models.CenterWeatherAdvisory CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Nws.OpenApiClient.Models.CenterWeatherAdvisory();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cwsu", n => { Cwsu = n.GetEnumValue<global::Soenneker.Nws.OpenApiClient.Models.NWSCenterWeatherServiceUnitId>(); } },
                { "end", n => { End = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "issueTime", n => { IssueTime = n.GetDateTimeOffsetValue(); } },
                { "observedProperty", n => { ObservedProperty = n.GetStringValue(); } },
                { "sequence", n => { Sequence = n.GetIntValue(); } },
                { "start", n => { Start = n.GetDateTimeOffsetValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Nws.OpenApiClient.Models.NWSCenterWeatherServiceUnitId>("cwsu", Cwsu);
            writer.WriteDateTimeOffsetValue("end", End);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("issueTime", IssueTime);
            writer.WriteStringValue("observedProperty", ObservedProperty);
            writer.WriteIntValue("sequence", Sequence);
            writer.WriteDateTimeOffsetValue("start", Start);
            writer.WriteStringValue("text", Text);
        }
    }
}
#pragma warning restore CS0618
