// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonLineString"/>, <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiLineString"/>, <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiPoint"/>, <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiPolygon"/>, <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonPoint"/>, <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonPolygon"/>, <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryMember1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GeoJsonGeometry : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonLineString"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonLineString? GeoJsonGeometryGeoJsonLineString { get; set; }
#nullable restore
#else
        public global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonLineString GeoJsonGeometryGeoJsonLineString { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiLineString"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiLineString? GeoJsonGeometryGeoJsonMultiLineString { get; set; }
#nullable restore
#else
        public global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiLineString GeoJsonGeometryGeoJsonMultiLineString { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiPoint"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiPoint? GeoJsonGeometryGeoJsonMultiPoint { get; set; }
#nullable restore
#else
        public global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiPoint GeoJsonGeometryGeoJsonMultiPoint { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiPolygon"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiPolygon? GeoJsonGeometryGeoJsonMultiPolygon { get; set; }
#nullable restore
#else
        public global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiPolygon GeoJsonGeometryGeoJsonMultiPolygon { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonPoint"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonPoint? GeoJsonGeometryGeoJsonPoint { get; set; }
#nullable restore
#else
        public global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonPoint GeoJsonGeometryGeoJsonPoint { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonPolygon"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonPolygon? GeoJsonGeometryGeoJsonPolygon { get; set; }
#nullable restore
#else
        public global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonPolygon GeoJsonGeometryGeoJsonPolygon { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryMember1? GeoJsonGeometryMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryMember1 GeoJsonGeometryMember1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometry"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometry CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometry();
            if("GeoJsonGeometryGeoJsonLineString".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GeoJsonGeometryGeoJsonLineString = new global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonLineString();
            }
            else if("GeoJsonGeometryGeoJsonMultiLineString".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GeoJsonGeometryGeoJsonMultiLineString = new global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiLineString();
            }
            else if("GeoJsonGeometryGeoJsonMultiPoint".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GeoJsonGeometryGeoJsonMultiPoint = new global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiPoint();
            }
            else if("GeoJsonGeometryGeoJsonMultiPolygon".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GeoJsonGeometryGeoJsonMultiPolygon = new global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiPolygon();
            }
            else if("GeoJsonGeometryGeoJsonPoint".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GeoJsonGeometryGeoJsonPoint = new global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonPoint();
            }
            else if("GeoJsonGeometryGeoJsonPolygon".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GeoJsonGeometryGeoJsonPolygon = new global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonPolygon();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(GeoJsonGeometryGeoJsonLineString != null)
            {
                return GeoJsonGeometryGeoJsonLineString.GetFieldDeserializers();
            }
            else if(GeoJsonGeometryGeoJsonMultiLineString != null)
            {
                return GeoJsonGeometryGeoJsonMultiLineString.GetFieldDeserializers();
            }
            else if(GeoJsonGeometryGeoJsonMultiPoint != null)
            {
                return GeoJsonGeometryGeoJsonMultiPoint.GetFieldDeserializers();
            }
            else if(GeoJsonGeometryGeoJsonMultiPolygon != null)
            {
                return GeoJsonGeometryGeoJsonMultiPolygon.GetFieldDeserializers();
            }
            else if(GeoJsonGeometryGeoJsonPoint != null)
            {
                return GeoJsonGeometryGeoJsonPoint.GetFieldDeserializers();
            }
            else if(GeoJsonGeometryGeoJsonPolygon != null)
            {
                return GeoJsonGeometryGeoJsonPolygon.GetFieldDeserializers();
            }
            else if(GeoJsonGeometryMember1 != null)
            {
                return GeoJsonGeometryMember1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(GeoJsonGeometryGeoJsonLineString != null)
            {
                writer.WriteObjectValue<global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonLineString>(null, GeoJsonGeometryGeoJsonLineString);
            }
            else if(GeoJsonGeometryGeoJsonMultiLineString != null)
            {
                writer.WriteObjectValue<global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiLineString>(null, GeoJsonGeometryGeoJsonMultiLineString);
            }
            else if(GeoJsonGeometryGeoJsonMultiPoint != null)
            {
                writer.WriteObjectValue<global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiPoint>(null, GeoJsonGeometryGeoJsonMultiPoint);
            }
            else if(GeoJsonGeometryGeoJsonMultiPolygon != null)
            {
                writer.WriteObjectValue<global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonMultiPolygon>(null, GeoJsonGeometryGeoJsonMultiPolygon);
            }
            else if(GeoJsonGeometryGeoJsonPoint != null)
            {
                writer.WriteObjectValue<global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonPoint>(null, GeoJsonGeometryGeoJsonPoint);
            }
            else if(GeoJsonGeometryGeoJsonPolygon != null)
            {
                writer.WriteObjectValue<global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryGeoJsonPolygon>(null, GeoJsonGeometryGeoJsonPolygon);
            }
            else if(GeoJsonGeometryMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Nws.OpenApiClient.Models.GeoJsonGeometryMember1>(null, GeoJsonGeometryMember1);
            }
        }
    }
}
#pragma warning restore CS0618
