// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GeoJsonGeometryMember3_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Polygon")]
        #pragma warning disable CS1591
        Polygon,
        #pragma warning restore CS1591
    }
}
