// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Gridpoint_Type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "wx:Gridpoint")]
        #pragma warning disable CS1591
        WxGridpoint,
        #pragma warning restore CS1591
    }
}
