// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    /// <summary>&quot;Marine region code. These are groups of marine areas combined.* AL: Alaska waters (PK)* AT: Atlantic Ocean (AM, AN)* GL: Great Lakes (LC, LE, LH, LM, LO, LS, SL)* GM: Gulf of Mexico (GM)* PA: Eastern Pacific Ocean and U.S. West Coast (PZ)* PI: Central and Western Pacific (PH, PM, PS)&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MarineRegionCode
    {
        [EnumMember(Value = "AL")]
        #pragma warning disable CS1591
        Al,
        #pragma warning restore CS1591
        [EnumMember(Value = "AT")]
        #pragma warning disable CS1591
        At,
        #pragma warning restore CS1591
        [EnumMember(Value = "GL")]
        #pragma warning disable CS1591
        Gl,
        #pragma warning restore CS1591
        [EnumMember(Value = "GM")]
        #pragma warning disable CS1591
        Gm,
        #pragma warning restore CS1591
        [EnumMember(Value = "PA")]
        #pragma warning disable CS1591
        Pa,
        #pragma warning restore CS1591
        [EnumMember(Value = "PI")]
        #pragma warning disable CS1591
        Pi,
        #pragma warning restore CS1591
    }
}
