// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OfficeBody : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Nws.OpenApiClient.Models.OfficeBodyAddress? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.Nws.OpenApiClient.Models.OfficeBodyAddress Address { get; set; }
#endif
        /// <summary>The approvedObservationStations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ApprovedObservationStations { get; set; }
#nullable restore
#else
        public List<string> ApprovedObservationStations { get; set; }
#endif
        /// <summary>The Context property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Nws.OpenApiClient.Models.JsonLdContext? Context { get; set; }
#nullable restore
#else
        public global::Soenneker.Nws.OpenApiClient.Models.JsonLdContext Context { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The faxNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FaxNumber { get; set; }
#nullable restore
#else
        public string FaxNumber { get; set; }
#endif
        /// <summary>The Id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The nwsRegion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NwsRegion { get; set; }
#nullable restore
#else
        public string NwsRegion { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OfficeBodyId { get; set; }
#nullable restore
#else
        public string OfficeBodyId { get; set; }
#endif
        /// <summary>The parentOrganization property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentOrganization { get; set; }
#nullable restore
#else
        public string ParentOrganization { get; set; }
#endif
        /// <summary>The responsibleCounties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ResponsibleCounties { get; set; }
#nullable restore
#else
        public List<string> ResponsibleCounties { get; set; }
#endif
        /// <summary>The responsibleFireZones property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ResponsibleFireZones { get; set; }
#nullable restore
#else
        public List<string> ResponsibleFireZones { get; set; }
#endif
        /// <summary>The responsibleForecastZones property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ResponsibleForecastZones { get; set; }
#nullable restore
#else
        public List<string> ResponsibleForecastZones { get; set; }
#endif
        /// <summary>The sameAs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SameAs { get; set; }
#nullable restore
#else
        public string SameAs { get; set; }
#endif
        /// <summary>The telephone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Telephone { get; set; }
#nullable restore
#else
        public string Telephone { get; set; }
#endif
        /// <summary>The Type property</summary>
        public global::Soenneker.Nws.OpenApiClient.Models.OfficeBodyType? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Models.OfficeBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Nws.OpenApiClient.Models.OfficeBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Nws.OpenApiClient.Models.OfficeBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.Nws.OpenApiClient.Models.OfficeBodyAddress>(global::Soenneker.Nws.OpenApiClient.Models.OfficeBodyAddress.CreateFromDiscriminatorValue); } },
                { "approvedObservationStations", n => { ApprovedObservationStations = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "@context", n => { Context = n.GetObjectValue<global::Soenneker.Nws.OpenApiClient.Models.JsonLdContext>(global::Soenneker.Nws.OpenApiClient.Models.JsonLdContext.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "faxNumber", n => { FaxNumber = n.GetStringValue(); } },
                { "@id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nwsRegion", n => { NwsRegion = n.GetStringValue(); } },
                { "id", n => { OfficeBodyId = n.GetStringValue(); } },
                { "parentOrganization", n => { ParentOrganization = n.GetStringValue(); } },
                { "responsibleCounties", n => { ResponsibleCounties = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "responsibleFireZones", n => { ResponsibleFireZones = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "responsibleForecastZones", n => { ResponsibleForecastZones = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "sameAs", n => { SameAs = n.GetStringValue(); } },
                { "telephone", n => { Telephone = n.GetStringValue(); } },
                { "@type", n => { Type = n.GetEnumValue<global::Soenneker.Nws.OpenApiClient.Models.OfficeBodyType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Nws.OpenApiClient.Models.OfficeBodyAddress>("address", Address);
            writer.WriteCollectionOfPrimitiveValues<string>("approvedObservationStations", ApprovedObservationStations);
            writer.WriteObjectValue<global::Soenneker.Nws.OpenApiClient.Models.JsonLdContext>("@context", Context);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("faxNumber", FaxNumber);
            writer.WriteStringValue("@id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("nwsRegion", NwsRegion);
            writer.WriteStringValue("id", OfficeBodyId);
            writer.WriteStringValue("parentOrganization", ParentOrganization);
            writer.WriteCollectionOfPrimitiveValues<string>("responsibleCounties", ResponsibleCounties);
            writer.WriteCollectionOfPrimitiveValues<string>("responsibleFireZones", ResponsibleFireZones);
            writer.WriteCollectionOfPrimitiveValues<string>("responsibleForecastZones", ResponsibleForecastZones);
            writer.WriteStringValue("sameAs", SameAs);
            writer.WriteStringValue("telephone", Telephone);
            writer.WriteEnumValue<global::Soenneker.Nws.OpenApiClient.Models.OfficeBodyType>("@type", Type);
        }
    }
}
#pragma warning restore CS0618
