// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Zones.Forecast.Item.Observations;
using Soenneker.Nws.OpenApiClient.Zones.Forecast.Item.Stations;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Nws.OpenApiClient.Zones.Forecast.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \zones\forecast\{zoneId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithZoneItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The observations property</summary>
        public global::Soenneker.Nws.OpenApiClient.Zones.Forecast.Item.Observations.ObservationsRequestBuilder Observations
        {
            get => new global::Soenneker.Nws.OpenApiClient.Zones.Forecast.Item.Observations.ObservationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stations property</summary>
        public global::Soenneker.Nws.OpenApiClient.Zones.Forecast.Item.Stations.StationsRequestBuilder Stations
        {
            get => new global::Soenneker.Nws.OpenApiClient.Zones.Forecast.Item.Stations.StationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Zones.Forecast.Item.WithZoneItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithZoneItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/zones/forecast/{zoneId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Zones.Forecast.Item.WithZoneItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithZoneItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/zones/forecast/{zoneId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
