// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Radar.Profilers;
using Soenneker.Nws.OpenApiClient.Radar.Queues;
using Soenneker.Nws.OpenApiClient.Radar.Servers;
using Soenneker.Nws.OpenApiClient.Radar.Stations;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Nws.OpenApiClient.Radar
{
    /// <summary>
    /// Builds and executes requests for operations under \radar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RadarRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The profilers property</summary>
        public global::Soenneker.Nws.OpenApiClient.Radar.Profilers.ProfilersRequestBuilder Profilers
        {
            get => new global::Soenneker.Nws.OpenApiClient.Radar.Profilers.ProfilersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queues property</summary>
        public global::Soenneker.Nws.OpenApiClient.Radar.Queues.QueuesRequestBuilder Queues
        {
            get => new global::Soenneker.Nws.OpenApiClient.Radar.Queues.QueuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The servers property</summary>
        public global::Soenneker.Nws.OpenApiClient.Radar.Servers.ServersRequestBuilder Servers
        {
            get => new global::Soenneker.Nws.OpenApiClient.Radar.Servers.ServersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stations property</summary>
        public global::Soenneker.Nws.OpenApiClient.Radar.Stations.StationsRequestBuilder Stations
        {
            get => new global::Soenneker.Nws.OpenApiClient.Radar.Stations.StationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Radar.RadarRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RadarRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/radar", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Radar.RadarRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RadarRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/radar", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
