// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Icons.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Nws.OpenApiClient.Icons.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \icons\{set}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSetItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Nws.OpenApiClient.icons.item.item collection</summary>
        /// <param name="position">.</param>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Icons.Item.Item.WithTimeOfDayItemRequestBuilder"/></returns>
        public global::Soenneker.Nws.OpenApiClient.Icons.Item.Item.WithTimeOfDayItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("timeOfDay", position);
                return new global::Soenneker.Nws.OpenApiClient.Icons.Item.Item.WithTimeOfDayItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Icons.Item.WithSetItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSetItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/icons/{set}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Icons.Item.WithSetItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSetItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/icons/{set}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
