// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Points.WithLatitudeWithLongitude;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Nws.OpenApiClient.Points
{
    /// <summary>
    /// Builds and executes requests for operations under \points
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PointsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Points.PointsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PointsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/points", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Points.PointsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PointsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/points", rawUrl)
        {
        }
        /// <summary>
        /// Builds and executes requests for operations under \points\{latitude},{longitude}
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Points.WithLatitudeWithLongitude.WithLatitudeWithLongitudeRequestBuilder"/></returns>
        /// <param name="latitude">Latitude</param>
        /// <param name="longitude">Longitude</param>
        public global::Soenneker.Nws.OpenApiClient.Points.WithLatitudeWithLongitude.WithLatitudeWithLongitudeRequestBuilder WithLatitudeWithLongitude(double? latitude, double? longitude)
        {
            if(ReferenceEquals(latitude, null)) throw new ArgumentNullException(nameof(latitude));
            if(ReferenceEquals(longitude, null)) throw new ArgumentNullException(nameof(longitude));
            return new global::Soenneker.Nws.OpenApiClient.Points.WithLatitudeWithLongitude.WithLatitudeWithLongitudeRequestBuilder(PathParameters, RequestAdapter, latitude, longitude);
        }
    }
}
#pragma warning restore CS0618
