// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Thumbnails.Satellite.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Nws.OpenApiClient.Thumbnails.Satellite
{
    /// <summary>
    /// Builds and executes requests for operations under \thumbnails\satellite
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SatelliteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Nws.OpenApiClient.thumbnails.satellite.item collection</summary>
        /// <param name="position">.</param>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Thumbnails.Satellite.Item.WithAreaItemRequestBuilder"/></returns>
        [Obsolete("")]
        public global::Soenneker.Nws.OpenApiClient.Thumbnails.Satellite.Item.WithAreaItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("area", position);
                return new global::Soenneker.Nws.OpenApiClient.Thumbnails.Satellite.Item.WithAreaItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Thumbnails.Satellite.SatelliteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SatelliteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/thumbnails/satellite", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Thumbnails.Satellite.SatelliteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SatelliteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/thumbnails/satellite", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
