// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Forecast;
using Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Stations;
using Soenneker.Nws.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY
{
    /// <summary>
    /// Builds and executes requests for operations under \gridpoints\{wfo}\{x},{y}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithXWithYRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The forecast property</summary>
        public global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Forecast.ForecastRequestBuilder Forecast
        {
            get => new global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Forecast.ForecastRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stations property</summary>
        public global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Stations.StationsRequestBuilder Stations
        {
            get => new global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Stations.StationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.WithXWithYRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        /// <param name="x">Forecast grid X coordinate</param>
        /// <param name="y">Forecast grid Y coordinate</param>
        public WithXWithYRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter, int? x = default, int? y = default) : base(requestAdapter, "{+baseurl}/gridpoints/{wfo}/{x},{y}", pathParameters)
        {
            if (x != null) PathParameters.Add("x", x);
            if (y != null) PathParameters.Add("y", y);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.WithXWithYRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithXWithYRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gridpoints/{wfo}/{x},{y}", rawUrl)
        {
        }
        /// <summary>
        /// Returns raw numerical forecast data for a 2.5km grid area
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Models.GridpointGeoJson"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Nws.OpenApiClient.Models.ProblemDetail">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Nws.OpenApiClient.Models.GridpointGeoJson?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Nws.OpenApiClient.Models.GridpointGeoJson> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Nws.OpenApiClient.Models.ProblemDetail.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Nws.OpenApiClient.Models.GridpointGeoJson>(requestInfo, global::Soenneker.Nws.OpenApiClient.Models.GridpointGeoJson.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns raw numerical forecast data for a 2.5km grid area
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/geo+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.WithXWithYRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.WithXWithYRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.WithXWithYRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithXWithYRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
