// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Offices.Item.Briefing.Download.Item;
using Soenneker.Nws.OpenApiClient.Offices.Item.Briefing.Download.Latest;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Nws.OpenApiClient.Offices.Item.Briefing.Download
{
    /// <summary>
    /// Builds and executes requests for operations under \offices\{officeId}\briefing\download
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DownloadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The latest property</summary>
        public global::Soenneker.Nws.OpenApiClient.Offices.Item.Briefing.Download.Latest.LatestRequestBuilder Latest
        {
            get => new global::Soenneker.Nws.OpenApiClient.Offices.Item.Briefing.Download.Latest.LatestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Nws.OpenApiClient.offices.item.briefing.download.item collection</summary>
        /// <param name="position">.</param>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Offices.Item.Briefing.Download.Item.WithBriefingItemRequestBuilder"/></returns>
        public global::Soenneker.Nws.OpenApiClient.Offices.Item.Briefing.Download.Item.WithBriefingItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("briefingId", position);
                return new global::Soenneker.Nws.OpenApiClient.Offices.Item.Briefing.Download.Item.WithBriefingItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Offices.Item.Briefing.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/offices/{officeId}/briefing/download", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Offices.Item.Briefing.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/offices/{officeId}/briefing/download", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
