// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Models;
using Soenneker.Nws.OpenApiClient.Radar.Stations.Item.Alarms;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Nws.OpenApiClient.Radar.Stations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \radar\stations\{stationId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithStationItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The alarms property</summary>
        public global::Soenneker.Nws.OpenApiClient.Radar.Stations.Item.Alarms.AlarmsRequestBuilder Alarms
        {
            get => new global::Soenneker.Nws.OpenApiClient.Radar.Stations.Item.Alarms.AlarmsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Radar.Stations.Item.WithStationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithStationItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/radar/stations/{stationId}{?host*,reportingHost*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Radar.Stations.Item.WithStationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithStationItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/radar/stations/{stationId}{?host*,reportingHost*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns metadata about a given radar station
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Models.RadarStation200ResponseResponseGeoJson"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Nws.OpenApiClient.Models.ProblemDetail">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Nws.OpenApiClient.Models.RadarStation200ResponseResponseGeoJson?> GetAsync(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Radar.Stations.Item.WithStationItemRequestBuilder.WithStationItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Nws.OpenApiClient.Models.RadarStation200ResponseResponseGeoJson> GetAsync(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Radar.Stations.Item.WithStationItemRequestBuilder.WithStationItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Nws.OpenApiClient.Models.ProblemDetail.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Nws.OpenApiClient.Models.RadarStation200ResponseResponseGeoJson>(requestInfo, global::Soenneker.Nws.OpenApiClient.Models.RadarStation200ResponseResponseGeoJson.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns metadata about a given radar station
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Radar.Stations.Item.WithStationItemRequestBuilder.WithStationItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Radar.Stations.Item.WithStationItemRequestBuilder.WithStationItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/geo+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Radar.Stations.Item.WithStationItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Nws.OpenApiClient.Radar.Stations.Item.WithStationItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Nws.OpenApiClient.Radar.Stations.Item.WithStationItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns metadata about a given radar station
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithStationItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Show latency info from specific LDM host</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("host")]
            public string? Host { get; set; }
#nullable restore
#else
            [QueryParameter("host")]
            public string Host { get; set; }
#endif
            /// <summary>Show RDA and latency info from specific reporting host</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("reportingHost")]
            public string? ReportingHost { get; set; }
#nullable restore
#else
            [QueryParameter("reportingHost")]
            public string ReportingHost { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
