// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Aviation.Cwsus.Item.Cwas.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Nws.OpenApiClient.Aviation.Cwsus.Item.Cwas.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \aviation\cwsus\{cwsuId}\cwas\{date}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDateItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Nws.OpenApiClient.aviation.cwsus.item.cwas.item.item collection</summary>
        /// <param name="position">Sequence number</param>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.Item.Cwas.Item.Item.WithSequenceItemRequestBuilder"/></returns>
        public global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.Item.Cwas.Item.Item.WithSequenceItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("sequence", position);
                return new global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.Item.Cwas.Item.Item.WithSequenceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Soenneker.Nws.OpenApiClient.aviation.cwsus.item.cwas.item.item collection</summary>
        /// <param name="position">Sequence number</param>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.Item.Cwas.Item.Item.WithSequenceItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.Item.Cwas.Item.Item.WithSequenceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("sequence", position);
                return new global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.Item.Cwas.Item.Item.WithSequenceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.Item.Cwas.Item.WithDateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDateItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aviation/cwsus/{cwsuId}/cwas/{date}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.Item.Cwas.Item.WithDateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDateItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aviation/cwsus/{cwsuId}/cwas/{date}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
