// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Models;
using Soenneker.Nws.OpenApiClient.Radar.Stations.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Nws.OpenApiClient.Radar.Stations
{
    /// <summary>
    /// Builds and executes requests for operations under \radar\stations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Nws.OpenApiClient.radar.stations.item collection</summary>
        /// <param name="position">Radar station ID</param>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Radar.Stations.Item.WithStationItemRequestBuilder"/></returns>
        public global::Soenneker.Nws.OpenApiClient.Radar.Stations.Item.WithStationItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("stationId", position);
                return new global::Soenneker.Nws.OpenApiClient.Radar.Stations.Item.WithStationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Radar.Stations.StationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/radar/stations{?host*,reportingHost*,stationType}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Radar.Stations.StationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/radar/stations{?host*,reportingHost*,stationType}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of radar stations
        /// </summary>
        /// <returns>A <see cref="UntypedNode"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Nws.OpenApiClient.Models.ProblemDetail">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<UntypedNode?> GetAsync(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Radar.Stations.StationsRequestBuilder.StationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<UntypedNode> GetAsync(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Radar.Stations.StationsRequestBuilder.StationsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Nws.OpenApiClient.Models.ProblemDetail.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<UntypedNode>(requestInfo, UntypedNode.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of radar stations
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Radar.Stations.StationsRequestBuilder.StationsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Radar.Stations.StationsRequestBuilder.StationsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/geo+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Radar.Stations.StationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Nws.OpenApiClient.Radar.Stations.StationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Nws.OpenApiClient.Radar.Stations.StationsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of radar stations
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class StationsRequestBuilderGetQueryParameters 
        {
            /// <summary>Show latency info from specific LDM host</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("host")]
            public string? Host { get; set; }
#nullable restore
#else
            [QueryParameter("host")]
            public string Host { get; set; }
#endif
            /// <summary>Show RDA and latency info from specific reporting host</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("reportingHost")]
            public string? ReportingHost { get; set; }
#nullable restore
#else
            [QueryParameter("reportingHost")]
            public string ReportingHost { get; set; }
#endif
            /// <summary>Limit results to a specific station type or types</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("stationType")]
            public string[]? StationType { get; set; }
#nullable restore
#else
            [QueryParameter("stationType")]
            public string[] StationType { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
