// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Aviation.Cwsus.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Nws.OpenApiClient.Aviation.Cwsus
{
    /// <summary>
    /// Builds and executes requests for operations under \aviation\cwsus
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CwsusRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Nws.OpenApiClient.aviation.cwsus.item collection</summary>
        /// <param name="position">NWS CWSU ID</param>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.Item.WithCwsuItemRequestBuilder"/></returns>
        public global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.Item.WithCwsuItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("cwsuId", position);
                return new global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.Item.WithCwsuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.CwsusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CwsusRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aviation/cwsus", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.CwsusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CwsusRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aviation/cwsus", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
