// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Stations.Item.Tafs.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Nws.OpenApiClient.Stations.Item.Tafs.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \stations\{stationId}\tafs\{date}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDateItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Nws.OpenApiClient.stations.item.tafs.item.item collection</summary>
        /// <param name="position">Time (HHMM format). This time is always specified in UTC (Zulu) time.</param>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Stations.Item.Tafs.Item.Item.WithTimeItemRequestBuilder"/></returns>
        public global::Soenneker.Nws.OpenApiClient.Stations.Item.Tafs.Item.Item.WithTimeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("time", position);
                return new global::Soenneker.Nws.OpenApiClient.Stations.Item.Tafs.Item.Item.WithTimeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Stations.Item.Tafs.Item.WithDateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDateItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/stations/{stationId}/tafs/{date}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Stations.Item.Tafs.Item.WithDateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDateItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/stations/{stationId}/tafs/{date}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
