// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    /// <summary>The code denoting the type of action recommended for the target audience.This corresponds to responseType in the CAP specification.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Alert_response
    {
        [EnumMember(Value = "Shelter")]
        #pragma warning disable CS1591
        Shelter,
        #pragma warning restore CS1591
        [EnumMember(Value = "Evacuate")]
        #pragma warning disable CS1591
        Evacuate,
        #pragma warning restore CS1591
        [EnumMember(Value = "Prepare")]
        #pragma warning disable CS1591
        Prepare,
        #pragma warning restore CS1591
        [EnumMember(Value = "Execute")]
        #pragma warning disable CS1591
        Execute,
        #pragma warning restore CS1591
        [EnumMember(Value = "Avoid")]
        #pragma warning disable CS1591
        Avoid,
        #pragma warning restore CS1591
        [EnumMember(Value = "Monitor")]
        #pragma warning disable CS1591
        Monitor,
        #pragma warning restore CS1591
        [EnumMember(Value = "Assess")]
        #pragma warning disable CS1591
        Assess,
        #pragma warning restore CS1591
        [EnumMember(Value = "AllClear")]
        #pragma warning disable CS1591
        AllClear,
        #pragma warning restore CS1591
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
    }
}
