// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AlertSeverity
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Extreme")]
        #pragma warning disable CS1591
        Extreme,
        #pragma warning restore CS1591
        [EnumMember(Value = "Severe")]
        #pragma warning disable CS1591
        Severe,
        #pragma warning restore CS1591
        [EnumMember(Value = "Moderate")]
        #pragma warning disable CS1591
        Moderate,
        #pragma warning restore CS1591
        [EnumMember(Value = "Minor")]
        #pragma warning disable CS1591
        Minor,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
