// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AlertCertainty
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Observed")]
        #pragma warning disable CS1591
        Observed,
        #pragma warning restore CS1591
        [EnumMember(Value = "Likely")]
        #pragma warning disable CS1591
        Likely,
        #pragma warning restore CS1591
        [EnumMember(Value = "Possible")]
        #pragma warning disable CS1591
        Possible,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unlikely")]
        #pragma warning disable CS1591
        Unlikely,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
