// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    /// <summary>
    /// An object representing sunrise, sunset, and twilight information for a location.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AstronomicalData : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The timestamp of the onset of astronomical twilight, defined as when the sun angle is 108° from vertical. This is the beginning of astronomical dawn and lasts until the nautical dawn.</summary>
        public DateTimeOffset? AstronomicalTwilightBegin { get; set; }
        /// <summary>The timestamp of the end of astronomical twilight, defined as when the sun angle is 108° from vertical. This is the end of astronomical dusk, which begins at the end of nautical twilight.</summary>
        public DateTimeOffset? AstronomicalTwilightEnd { get; set; }
        /// <summary>The timestamp of the onset of civil twilight, defined as when the sun angle is 96° from vertical. This is the beginning of civil dawn and lasts until sunrise.</summary>
        public DateTimeOffset? CivilTwilightBegin { get; set; }
        /// <summary>The timestamp of the end of civil twilight, defined as when the sun angle is 96° from vertical. This is the end of civil dusk, which begins at sunset.</summary>
        public DateTimeOffset? CivilTwilightEnd { get; set; }
        /// <summary>The timestamp of the onset of nautical twilight, defined as when the sun angle is 102° from vertical. This is the beginning of nautical dawn and lasts until the civil dawn.</summary>
        public DateTimeOffset? NauticalTwilightBegin { get; set; }
        /// <summary>The timestamp of the end of nautical twilight, defined as when the sun angle is 102° from vertical. This is the end of nautical dusk, which begins at the end of civil twilight.</summary>
        public DateTimeOffset? NauticalTwilightEnd { get; set; }
        /// <summary>The timestamp of sunrise, defined as when the sun angle is 90°35&apos; from vertical.</summary>
        public DateTimeOffset? Sunrise { get; set; }
        /// <summary>The timestamp of sunset, defined as when the sun angle is 90°35&apos; from vertical.</summary>
        public DateTimeOffset? Sunset { get; set; }
        /// <summary>The timestamp when the sun reaches its zenith.</summary>
        public DateTimeOffset? Transit { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Models.AstronomicalData"/> and sets the default values.
        /// </summary>
        public AstronomicalData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Models.AstronomicalData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Nws.OpenApiClient.Models.AstronomicalData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Nws.OpenApiClient.Models.AstronomicalData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "astronomicalTwilightBegin", n => { AstronomicalTwilightBegin = n.GetDateTimeOffsetValue(); } },
                { "astronomicalTwilightEnd", n => { AstronomicalTwilightEnd = n.GetDateTimeOffsetValue(); } },
                { "civilTwilightBegin", n => { CivilTwilightBegin = n.GetDateTimeOffsetValue(); } },
                { "civilTwilightEnd", n => { CivilTwilightEnd = n.GetDateTimeOffsetValue(); } },
                { "nauticalTwilightBegin", n => { NauticalTwilightBegin = n.GetDateTimeOffsetValue(); } },
                { "nauticalTwilightEnd", n => { NauticalTwilightEnd = n.GetDateTimeOffsetValue(); } },
                { "sunrise", n => { Sunrise = n.GetDateTimeOffsetValue(); } },
                { "sunset", n => { Sunset = n.GetDateTimeOffsetValue(); } },
                { "transit", n => { Transit = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("astronomicalTwilightBegin", AstronomicalTwilightBegin);
            writer.WriteDateTimeOffsetValue("astronomicalTwilightEnd", AstronomicalTwilightEnd);
            writer.WriteDateTimeOffsetValue("civilTwilightBegin", CivilTwilightBegin);
            writer.WriteDateTimeOffsetValue("civilTwilightEnd", CivilTwilightEnd);
            writer.WriteDateTimeOffsetValue("nauticalTwilightBegin", NauticalTwilightBegin);
            writer.WriteDateTimeOffsetValue("nauticalTwilightEnd", NauticalTwilightEnd);
            writer.WriteDateTimeOffsetValue("sunrise", Sunrise);
            writer.WriteDateTimeOffsetValue("sunset", Sunset);
            writer.WriteDateTimeOffsetValue("transit", Transit);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
