// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Gridpoint_weather_values_value_weather
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "blowing_dust")]
        #pragma warning disable CS1591
        Blowing_dust,
        #pragma warning restore CS1591
        [EnumMember(Value = "blowing_sand")]
        #pragma warning disable CS1591
        Blowing_sand,
        #pragma warning restore CS1591
        [EnumMember(Value = "blowing_snow")]
        #pragma warning disable CS1591
        Blowing_snow,
        #pragma warning restore CS1591
        [EnumMember(Value = "drizzle")]
        #pragma warning disable CS1591
        Drizzle,
        #pragma warning restore CS1591
        [EnumMember(Value = "fog")]
        #pragma warning disable CS1591
        Fog,
        #pragma warning restore CS1591
        [EnumMember(Value = "freezing_fog")]
        #pragma warning disable CS1591
        Freezing_fog,
        #pragma warning restore CS1591
        [EnumMember(Value = "freezing_drizzle")]
        #pragma warning disable CS1591
        Freezing_drizzle,
        #pragma warning restore CS1591
        [EnumMember(Value = "freezing_rain")]
        #pragma warning disable CS1591
        Freezing_rain,
        #pragma warning restore CS1591
        [EnumMember(Value = "freezing_spray")]
        #pragma warning disable CS1591
        Freezing_spray,
        #pragma warning restore CS1591
        [EnumMember(Value = "frost")]
        #pragma warning disable CS1591
        Frost,
        #pragma warning restore CS1591
        [EnumMember(Value = "hail")]
        #pragma warning disable CS1591
        Hail,
        #pragma warning restore CS1591
        [EnumMember(Value = "haze")]
        #pragma warning disable CS1591
        Haze,
        #pragma warning restore CS1591
        [EnumMember(Value = "ice_crystals")]
        #pragma warning disable CS1591
        Ice_crystals,
        #pragma warning restore CS1591
        [EnumMember(Value = "ice_fog")]
        #pragma warning disable CS1591
        Ice_fog,
        #pragma warning restore CS1591
        [EnumMember(Value = "rain")]
        #pragma warning disable CS1591
        Rain,
        #pragma warning restore CS1591
        [EnumMember(Value = "rain_showers")]
        #pragma warning disable CS1591
        Rain_showers,
        #pragma warning restore CS1591
        [EnumMember(Value = "sleet")]
        #pragma warning disable CS1591
        Sleet,
        #pragma warning restore CS1591
        [EnumMember(Value = "smoke")]
        #pragma warning disable CS1591
        Smoke,
        #pragma warning restore CS1591
        [EnumMember(Value = "snow")]
        #pragma warning disable CS1591
        Snow,
        #pragma warning restore CS1591
        [EnumMember(Value = "snow_showers")]
        #pragma warning disable CS1591
        Snow_showers,
        #pragma warning restore CS1591
        [EnumMember(Value = "thunderstorms")]
        #pragma warning disable CS1591
        Thunderstorms,
        #pragma warning restore CS1591
        [EnumMember(Value = "volcanic_ash")]
        #pragma warning disable CS1591
        Volcanic_ash,
        #pragma warning restore CS1591
        [EnumMember(Value = "water_spouts")]
        #pragma warning disable CS1591
        Water_spouts,
        #pragma warning restore CS1591
    }
}
