// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Gridpoint_weather_values_value_attributes
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "damaging_wind")]
        #pragma warning disable CS1591
        Damaging_wind,
        #pragma warning restore CS1591
        [EnumMember(Value = "dry_thunderstorms")]
        #pragma warning disable CS1591
        Dry_thunderstorms,
        #pragma warning restore CS1591
        [EnumMember(Value = "flooding")]
        #pragma warning disable CS1591
        Flooding,
        #pragma warning restore CS1591
        [EnumMember(Value = "gusty_wind")]
        #pragma warning disable CS1591
        Gusty_wind,
        #pragma warning restore CS1591
        [EnumMember(Value = "heavy_rain")]
        #pragma warning disable CS1591
        Heavy_rain,
        #pragma warning restore CS1591
        [EnumMember(Value = "large_hail")]
        #pragma warning disable CS1591
        Large_hail,
        #pragma warning restore CS1591
        [EnumMember(Value = "small_hail")]
        #pragma warning disable CS1591
        Small_hail,
        #pragma warning restore CS1591
        [EnumMember(Value = "tornadoes")]
        #pragma warning disable CS1591
        Tornadoes,
        #pragma warning restore CS1591
    }
}
