// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    /// <summary>If not null, indicates a non-diurnal temperature trend for the period (either rising temperature overnight, or falling temperature during the day)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GridpointHourlyForecastPeriod_temperatureTrend
    {
        [EnumMember(Value = "rising")]
        #pragma warning disable CS1591
        Rising,
        #pragma warning restore CS1591
        [EnumMember(Value = "falling")]
        #pragma warning disable CS1591
        Falling,
        #pragma warning restore CS1591
    }
}
