// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Gridpoint_weather_values_value_coverage
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "areas")]
        #pragma warning disable CS1591
        Areas,
        #pragma warning restore CS1591
        [EnumMember(Value = "brief")]
        #pragma warning disable CS1591
        Brief,
        #pragma warning restore CS1591
        [EnumMember(Value = "chance")]
        #pragma warning disable CS1591
        Chance,
        #pragma warning restore CS1591
        [EnumMember(Value = "definite")]
        #pragma warning disable CS1591
        Definite,
        #pragma warning restore CS1591
        [EnumMember(Value = "few")]
        #pragma warning disable CS1591
        Few,
        #pragma warning restore CS1591
        [EnumMember(Value = "frequent")]
        #pragma warning disable CS1591
        Frequent,
        #pragma warning restore CS1591
        [EnumMember(Value = "intermittent")]
        #pragma warning disable CS1591
        Intermittent,
        #pragma warning restore CS1591
        [EnumMember(Value = "isolated")]
        #pragma warning disable CS1591
        Isolated,
        #pragma warning restore CS1591
        [EnumMember(Value = "likely")]
        #pragma warning disable CS1591
        Likely,
        #pragma warning restore CS1591
        [EnumMember(Value = "numerous")]
        #pragma warning disable CS1591
        Numerous,
        #pragma warning restore CS1591
        [EnumMember(Value = "occasional")]
        #pragma warning disable CS1591
        Occasional,
        #pragma warning restore CS1591
        [EnumMember(Value = "patchy")]
        #pragma warning disable CS1591
        Patchy,
        #pragma warning restore CS1591
        [EnumMember(Value = "periods")]
        #pragma warning disable CS1591
        Periods,
        #pragma warning restore CS1591
        [EnumMember(Value = "scattered")]
        #pragma warning disable CS1591
        Scattered,
        #pragma warning restore CS1591
        [EnumMember(Value = "slight_chance")]
        #pragma warning disable CS1591
        Slight_chance,
        #pragma warning restore CS1591
        [EnumMember(Value = "widespread")]
        #pragma warning disable CS1591
        Widespread,
        #pragma warning restore CS1591
    }
}
