// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MetarPhenomenon_intensity
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "light")]
        #pragma warning disable CS1591
        Light,
        #pragma warning restore CS1591
        [EnumMember(Value = "heavy")]
        #pragma warning disable CS1591
        Heavy,
        #pragma warning restore CS1591
    }
}
