// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MetarSkyCoverage
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "OVC")]
        #pragma warning disable CS1591
        OVC,
        #pragma warning restore CS1591
        [EnumMember(Value = "BKN")]
        #pragma warning disable CS1591
        BKN,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCT")]
        #pragma warning disable CS1591
        SCT,
        #pragma warning restore CS1591
        [EnumMember(Value = "FEW")]
        #pragma warning disable CS1591
        FEW,
        #pragma warning restore CS1591
        [EnumMember(Value = "SKC")]
        #pragma warning disable CS1591
        SKC,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLR")]
        #pragma warning disable CS1591
        CLR,
        #pragma warning restore CS1591
        [EnumMember(Value = "VV")]
        #pragma warning disable CS1591
        VV,
        #pragma warning restore CS1591
    }
}
