// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    /// <summary>For values in observation records, the quality control flag from the MADIS system. The definitions of these flags can be found at https://madis.ncep.noaa.gov/madis_sfc_qc_notes.shtml</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum QuantitativeValue_qualityControl
    {
        [EnumMember(Value = "Z")]
        #pragma warning disable CS1591
        Z,
        #pragma warning restore CS1591
        [EnumMember(Value = "C")]
        #pragma warning disable CS1591
        C,
        #pragma warning restore CS1591
        [EnumMember(Value = "S")]
        #pragma warning disable CS1591
        S,
        #pragma warning restore CS1591
        [EnumMember(Value = "V")]
        #pragma warning disable CS1591
        V,
        #pragma warning restore CS1591
        [EnumMember(Value = "X")]
        #pragma warning disable CS1591
        X,
        #pragma warning restore CS1591
        [EnumMember(Value = "Q")]
        #pragma warning disable CS1591
        Q,
        #pragma warning restore CS1591
        [EnumMember(Value = "G")]
        #pragma warning disable CS1591
        G,
        #pragma warning restore CS1591
        [EnumMember(Value = "B")]
        #pragma warning disable CS1591
        B,
        #pragma warning restore CS1591
        [EnumMember(Value = "T")]
        #pragma warning disable CS1591
        T,
        #pragma warning restore CS1591
    }
}
