// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Nws.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum StateTerritoryCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "AL")]
        #pragma warning disable CS1591
        AL,
        #pragma warning restore CS1591
        [EnumMember(Value = "AK")]
        #pragma warning disable CS1591
        AK,
        #pragma warning restore CS1591
        [EnumMember(Value = "AS")]
        #pragma warning disable CS1591
        AS,
        #pragma warning restore CS1591
        [EnumMember(Value = "AR")]
        #pragma warning disable CS1591
        AR,
        #pragma warning restore CS1591
        [EnumMember(Value = "AZ")]
        #pragma warning disable CS1591
        AZ,
        #pragma warning restore CS1591
        [EnumMember(Value = "CA")]
        #pragma warning disable CS1591
        CA,
        #pragma warning restore CS1591
        [EnumMember(Value = "CO")]
        #pragma warning disable CS1591
        CO,
        #pragma warning restore CS1591
        [EnumMember(Value = "CT")]
        #pragma warning disable CS1591
        CT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DE")]
        #pragma warning disable CS1591
        DE,
        #pragma warning restore CS1591
        [EnumMember(Value = "DC")]
        #pragma warning disable CS1591
        DC,
        #pragma warning restore CS1591
        [EnumMember(Value = "FL")]
        #pragma warning disable CS1591
        FL,
        #pragma warning restore CS1591
        [EnumMember(Value = "GA")]
        #pragma warning disable CS1591
        GA,
        #pragma warning restore CS1591
        [EnumMember(Value = "GU")]
        #pragma warning disable CS1591
        GU,
        #pragma warning restore CS1591
        [EnumMember(Value = "HI")]
        #pragma warning disable CS1591
        HI,
        #pragma warning restore CS1591
        [EnumMember(Value = "ID")]
        #pragma warning disable CS1591
        ID,
        #pragma warning restore CS1591
        [EnumMember(Value = "IL")]
        #pragma warning disable CS1591
        IL,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN")]
        #pragma warning disable CS1591
        IN,
        #pragma warning restore CS1591
        [EnumMember(Value = "IA")]
        #pragma warning disable CS1591
        IA,
        #pragma warning restore CS1591
        [EnumMember(Value = "KS")]
        #pragma warning disable CS1591
        KS,
        #pragma warning restore CS1591
        [EnumMember(Value = "KY")]
        #pragma warning disable CS1591
        KY,
        #pragma warning restore CS1591
        [EnumMember(Value = "LA")]
        #pragma warning disable CS1591
        LA,
        #pragma warning restore CS1591
        [EnumMember(Value = "ME")]
        #pragma warning disable CS1591
        ME,
        #pragma warning restore CS1591
        [EnumMember(Value = "MD")]
        #pragma warning disable CS1591
        MD,
        #pragma warning restore CS1591
        [EnumMember(Value = "MA")]
        #pragma warning disable CS1591
        MA,
        #pragma warning restore CS1591
        [EnumMember(Value = "MI")]
        #pragma warning disable CS1591
        MI,
        #pragma warning restore CS1591
        [EnumMember(Value = "MN")]
        #pragma warning disable CS1591
        MN,
        #pragma warning restore CS1591
        [EnumMember(Value = "MS")]
        #pragma warning disable CS1591
        MS,
        #pragma warning restore CS1591
        [EnumMember(Value = "MO")]
        #pragma warning disable CS1591
        MO,
        #pragma warning restore CS1591
        [EnumMember(Value = "MT")]
        #pragma warning disable CS1591
        MT,
        #pragma warning restore CS1591
        [EnumMember(Value = "NE")]
        #pragma warning disable CS1591
        NE,
        #pragma warning restore CS1591
        [EnumMember(Value = "NV")]
        #pragma warning disable CS1591
        NV,
        #pragma warning restore CS1591
        [EnumMember(Value = "NH")]
        #pragma warning disable CS1591
        NH,
        #pragma warning restore CS1591
        [EnumMember(Value = "NJ")]
        #pragma warning disable CS1591
        NJ,
        #pragma warning restore CS1591
        [EnumMember(Value = "NM")]
        #pragma warning disable CS1591
        NM,
        #pragma warning restore CS1591
        [EnumMember(Value = "NY")]
        #pragma warning disable CS1591
        NY,
        #pragma warning restore CS1591
        [EnumMember(Value = "NC")]
        #pragma warning disable CS1591
        NC,
        #pragma warning restore CS1591
        [EnumMember(Value = "ND")]
        #pragma warning disable CS1591
        ND,
        #pragma warning restore CS1591
        [EnumMember(Value = "OH")]
        #pragma warning disable CS1591
        OH,
        #pragma warning restore CS1591
        [EnumMember(Value = "OK")]
        #pragma warning disable CS1591
        OK,
        #pragma warning restore CS1591
        [EnumMember(Value = "OR")]
        #pragma warning disable CS1591
        OR,
        #pragma warning restore CS1591
        [EnumMember(Value = "PA")]
        #pragma warning disable CS1591
        PA,
        #pragma warning restore CS1591
        [EnumMember(Value = "PR")]
        #pragma warning disable CS1591
        PR,
        #pragma warning restore CS1591
        [EnumMember(Value = "RI")]
        #pragma warning disable CS1591
        RI,
        #pragma warning restore CS1591
        [EnumMember(Value = "SC")]
        #pragma warning disable CS1591
        SC,
        #pragma warning restore CS1591
        [EnumMember(Value = "SD")]
        #pragma warning disable CS1591
        SD,
        #pragma warning restore CS1591
        [EnumMember(Value = "TN")]
        #pragma warning disable CS1591
        TN,
        #pragma warning restore CS1591
        [EnumMember(Value = "TX")]
        #pragma warning disable CS1591
        TX,
        #pragma warning restore CS1591
        [EnumMember(Value = "UT")]
        #pragma warning disable CS1591
        UT,
        #pragma warning restore CS1591
        [EnumMember(Value = "VT")]
        #pragma warning disable CS1591
        VT,
        #pragma warning restore CS1591
        [EnumMember(Value = "VI")]
        #pragma warning disable CS1591
        VI,
        #pragma warning restore CS1591
        [EnumMember(Value = "VA")]
        #pragma warning disable CS1591
        VA,
        #pragma warning restore CS1591
        [EnumMember(Value = "WA")]
        #pragma warning disable CS1591
        WA,
        #pragma warning restore CS1591
        [EnumMember(Value = "WV")]
        #pragma warning disable CS1591
        WV,
        #pragma warning restore CS1591
        [EnumMember(Value = "WI")]
        #pragma warning disable CS1591
        WI,
        #pragma warning restore CS1591
        [EnumMember(Value = "WY")]
        #pragma warning disable CS1591
        WY,
        #pragma warning restore CS1591
        [EnumMember(Value = "MP")]
        #pragma warning disable CS1591
        MP,
        #pragma warning restore CS1591
        [EnumMember(Value = "PW")]
        #pragma warning disable CS1591
        PW,
        #pragma warning restore CS1591
        [EnumMember(Value = "FM")]
        #pragma warning disable CS1591
        FM,
        #pragma warning restore CS1591
        [EnumMember(Value = "MH")]
        #pragma warning disable CS1591
        MH,
        #pragma warning restore CS1591
    }
}
