// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Nws.OpenApiClient.Alerts;
using Soenneker.Nws.OpenApiClient.Aviation;
using Soenneker.Nws.OpenApiClient.Glossary;
using Soenneker.Nws.OpenApiClient.Gridpoints;
using Soenneker.Nws.OpenApiClient.Icons;
using Soenneker.Nws.OpenApiClient.Offices;
using Soenneker.Nws.OpenApiClient.Points;
using Soenneker.Nws.OpenApiClient.Products;
using Soenneker.Nws.OpenApiClient.Radar;
using Soenneker.Nws.OpenApiClient.Radio;
using Soenneker.Nws.OpenApiClient.Stations;
using Soenneker.Nws.OpenApiClient.Thumbnails;
using Soenneker.Nws.OpenApiClient.Zones;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Nws.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NwsOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The alerts property</summary>
        public global::Soenneker.Nws.OpenApiClient.Alerts.AlertsRequestBuilder Alerts
        {
            get => new global::Soenneker.Nws.OpenApiClient.Alerts.AlertsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The aviation property</summary>
        public global::Soenneker.Nws.OpenApiClient.Aviation.AviationRequestBuilder Aviation
        {
            get => new global::Soenneker.Nws.OpenApiClient.Aviation.AviationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The glossary property</summary>
        public global::Soenneker.Nws.OpenApiClient.Glossary.GlossaryRequestBuilder Glossary
        {
            get => new global::Soenneker.Nws.OpenApiClient.Glossary.GlossaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gridpoints property</summary>
        public global::Soenneker.Nws.OpenApiClient.Gridpoints.GridpointsRequestBuilder Gridpoints
        {
            get => new global::Soenneker.Nws.OpenApiClient.Gridpoints.GridpointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The icons property</summary>
        public global::Soenneker.Nws.OpenApiClient.Icons.IconsRequestBuilder Icons
        {
            get => new global::Soenneker.Nws.OpenApiClient.Icons.IconsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The offices property</summary>
        public global::Soenneker.Nws.OpenApiClient.Offices.OfficesRequestBuilder Offices
        {
            get => new global::Soenneker.Nws.OpenApiClient.Offices.OfficesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The points property</summary>
        public global::Soenneker.Nws.OpenApiClient.Points.PointsRequestBuilder Points
        {
            get => new global::Soenneker.Nws.OpenApiClient.Points.PointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The products property</summary>
        public global::Soenneker.Nws.OpenApiClient.Products.ProductsRequestBuilder Products
        {
            get => new global::Soenneker.Nws.OpenApiClient.Products.ProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The radar property</summary>
        public global::Soenneker.Nws.OpenApiClient.Radar.RadarRequestBuilder Radar
        {
            get => new global::Soenneker.Nws.OpenApiClient.Radar.RadarRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The radio property</summary>
        public global::Soenneker.Nws.OpenApiClient.Radio.RadioRequestBuilder Radio
        {
            get => new global::Soenneker.Nws.OpenApiClient.Radio.RadioRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stations property</summary>
        public global::Soenneker.Nws.OpenApiClient.Stations.StationsRequestBuilder Stations
        {
            get => new global::Soenneker.Nws.OpenApiClient.Stations.StationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The thumbnails property</summary>
        public global::Soenneker.Nws.OpenApiClient.Thumbnails.ThumbnailsRequestBuilder Thumbnails
        {
            get => new global::Soenneker.Nws.OpenApiClient.Thumbnails.ThumbnailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The zones property</summary>
        public global::Soenneker.Nws.OpenApiClient.Zones.ZonesRequestBuilder Zones
        {
            get => new global::Soenneker.Nws.OpenApiClient.Zones.ZonesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.NwsOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NwsOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.weather.gov";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
