// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Models;
using Soenneker.Nws.OpenApiClient.Zones.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Nws.OpenApiClient.Zones.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \zones\{type}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTypeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Nws.OpenApiClient.zones.item.item collection</summary>
        /// <param name="position">NWS public zone/county identifier</param>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Zones.Item.Item.WithZoneItemRequestBuilder"/></returns>
        public global::Soenneker.Nws.OpenApiClient.Zones.Item.Item.WithZoneItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("zoneId", position);
                return new global::Soenneker.Nws.OpenApiClient.Zones.Item.Item.WithZoneItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Zones.Item.WithTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTypeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/zones/{type}{?area,effective*,id,include_geometry*,limit*,point*,region,type}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Zones.Item.WithTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTypeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/zones/{type}{?area,effective*,id,include_geometry*,limit*,point*,region,type}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of zones of a given type
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Models.ZoneCollectionGeoJson"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Nws.OpenApiClient.Models.ProblemDetail">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Nws.OpenApiClient.Models.ZoneCollectionGeoJson?> GetAsync(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Zones.Item.WithTypeItemRequestBuilder.WithTypeItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Nws.OpenApiClient.Models.ZoneCollectionGeoJson> GetAsync(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Zones.Item.WithTypeItemRequestBuilder.WithTypeItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Nws.OpenApiClient.Models.ProblemDetail.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Nws.OpenApiClient.Models.ZoneCollectionGeoJson>(requestInfo, global::Soenneker.Nws.OpenApiClient.Models.ZoneCollectionGeoJson.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of zones of a given type
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Zones.Item.WithTypeItemRequestBuilder.WithTypeItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Zones.Item.WithTypeItemRequestBuilder.WithTypeItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/geo+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Zones.Item.WithTypeItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Nws.OpenApiClient.Zones.Item.WithTypeItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Nws.OpenApiClient.Zones.Item.WithTypeItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of zones of a given type
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithTypeItemRequestBuilderGetQueryParameters 
        {
            /// <summary>State/marine area code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("area")]
            public string[]? Area { get; set; }
#nullable restore
#else
            [QueryParameter("area")]
            public string[] Area { get; set; }
#endif
            /// <summary>Effective date/time</summary>
            [QueryParameter("effective")]
            public DateTimeOffset? Effective { get; set; }
            /// <summary>Zone ID (forecast or county)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("id")]
            public string[]? Id { get; set; }
#nullable restore
#else
            [QueryParameter("id")]
            public string[] Id { get; set; }
#endif
            /// <summary>Include geometry in results (true/false)</summary>
            [QueryParameter("include_geometry")]
            public bool? IncludeGeometry { get; set; }
            /// <summary>Limit</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Point (latitude,longitude)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("point")]
            public string? Point { get; set; }
#nullable restore
#else
            [QueryParameter("point")]
            public string Point { get; set; }
#endif
            /// <summary>Region code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("region")]
            public string[]? Region { get; set; }
#nullable restore
#else
            [QueryParameter("region")]
            public string[] Region { get; set; }
#endif
            /// <summary>Zone type</summary>
            [Obsolete("This property is deprecated, use TypeAsNWSZoneType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("type")]
            public string[]? Type { get; set; }
#nullable restore
#else
            [QueryParameter("type")]
            public string[] Type { get; set; }
#endif
            /// <summary>Zone type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("type")]
            public global::Soenneker.Nws.OpenApiClient.Models.NWSZoneType[]? TypeAsNWSZoneType { get; set; }
#nullable restore
#else
            [QueryParameter("type")]
            public global::Soenneker.Nws.OpenApiClient.Models.NWSZoneType[] TypeAsNWSZoneType { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithTypeItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Zones.Item.WithTypeItemRequestBuilder.WithTypeItemRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
