// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Gridpoints.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Nws.OpenApiClient.Gridpoints
{
    /// <summary>
    /// Builds and executes requests for operations under \gridpoints
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GridpointsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Nws.OpenApiClient.gridpoints.item collection</summary>
        /// <param name="position">Forecast office ID</param>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithWfoItemRequestBuilder"/></returns>
        public global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithWfoItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("wfo", position);
                return new global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithWfoItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Gridpoints.GridpointsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GridpointsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gridpoints", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Gridpoints.GridpointsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GridpointsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gridpoints", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
