// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Nws.OpenApiClient.Gridpoints.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \gridpoints\{wfo}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithWfoItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithWfoItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWfoItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gridpoints/{wfo}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithWfoItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWfoItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gridpoints/{wfo}", rawUrl)
        {
        }
        /// <summary>
        /// Builds and executes requests for operations under \gridpoints\{wfo}\{x},{y}
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.WithXWithYRequestBuilder"/></returns>
        /// <param name="x">Forecast grid X coordinate</param>
        /// <param name="y">Forecast grid Y coordinate</param>
        public global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.WithXWithYRequestBuilder WithXWithY(int? x, int? y)
        {
            if(ReferenceEquals(x, null)) throw new ArgumentNullException(nameof(x));
            if(ReferenceEquals(y, null)) throw new ArgumentNullException(nameof(y));
            return new global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.WithXWithYRequestBuilder(PathParameters, RequestAdapter, x, y);
        }
    }
}
#pragma warning restore CS0618
