// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Forecast.Hourly
{
    /// <summary>
    /// Builds and executes requests for operations under \gridpoints\{wfo}\{x},{y}\forecast\hourly
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HourlyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Forecast.Hourly.HourlyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HourlyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gridpoints/{wfo}/{x},{y}/forecast/hourly{?units*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Forecast.Hourly.HourlyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HourlyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gridpoints/{wfo}/{x},{y}/forecast/hourly{?units*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a textual hourly forecast for a 2.5km grid area
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Models.GridpointHourlyForecastGeoJson"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Nws.OpenApiClient.Models.ProblemDetail">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Nws.OpenApiClient.Models.GridpointHourlyForecastGeoJson?> GetAsync(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Forecast.Hourly.HourlyRequestBuilder.HourlyRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Nws.OpenApiClient.Models.GridpointHourlyForecastGeoJson> GetAsync(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Forecast.Hourly.HourlyRequestBuilder.HourlyRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Nws.OpenApiClient.Models.ProblemDetail.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Nws.OpenApiClient.Models.GridpointHourlyForecastGeoJson>(requestInfo, global::Soenneker.Nws.OpenApiClient.Models.GridpointHourlyForecastGeoJson.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a textual hourly forecast for a 2.5km grid area
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Forecast.Hourly.HourlyRequestBuilder.HourlyRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Forecast.Hourly.HourlyRequestBuilder.HourlyRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/geo+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Forecast.Hourly.HourlyRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Forecast.Hourly.HourlyRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Forecast.Hourly.HourlyRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a textual hourly forecast for a 2.5km grid area
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class HourlyRequestBuilderGetQueryParameters 
        {
            /// <summary>Use US customary or SI (metric) units in textual output</summary>
            [Obsolete("This property is deprecated, use UnitsAsGridpointForecastUnits instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("units")]
            public string? Units { get; set; }
#nullable restore
#else
            [QueryParameter("units")]
            public string Units { get; set; }
#endif
            /// <summary>Use US customary or SI (metric) units in textual output</summary>
            [QueryParameter("units")]
            public global::Soenneker.Nws.OpenApiClient.Models.GridpointForecastUnits? UnitsAsGridpointForecastUnits { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class HourlyRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Nws.OpenApiClient.Gridpoints.Item.WithXWithY.Forecast.Hourly.HourlyRequestBuilder.HourlyRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
