// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Nws.OpenApiClient.Aviation.Cwsus;
using Soenneker.Nws.OpenApiClient.Aviation.Sigmets;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Nws.OpenApiClient.Aviation
{
    /// <summary>
    /// Builds and executes requests for operations under \aviation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AviationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cwsus property</summary>
        public global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.CwsusRequestBuilder Cwsus
        {
            get => new global::Soenneker.Nws.OpenApiClient.Aviation.Cwsus.CwsusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sigmets property</summary>
        public global::Soenneker.Nws.OpenApiClient.Aviation.Sigmets.SigmetsRequestBuilder Sigmets
        {
            get => new global::Soenneker.Nws.OpenApiClient.Aviation.Sigmets.SigmetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Aviation.AviationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AviationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aviation", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Nws.OpenApiClient.Aviation.AviationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AviationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aviation", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
